name: Build & Tests

on:
  push:
    branches: [ 2.x, master ]
  pull_request:
    branches: [ 2.x, master ]

jobs:
  build:
    strategy:
      matrix:
        xcode: ['xcode26', 'xcode16.4']
        include:
            - xcode: 'xcode16.4'
              xcode-path: '/Applications/Xcode_16.4.app/Contents/Developer'
              upload-dist: true
              run-analyzer: true
              macos: 'macos-15'
            - xcode: 'xcode26'
              xcode-path: '/Applications/Xcode_26.0.app'
              upload-dist: false
              run-analyzer: false
              macos: 'macos-15'
            
    name: Build and Test Sparkle
    runs-on: ${{ matrix.macos }}

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Build Unit Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild build-for-testing -project Sparkle.xcodeproj -scheme Distribution -enableCodeCoverage YES -derivedDataPath build
      - name: Run Unit Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild test-without-building -project Sparkle.xcodeproj -scheme Distribution -enableCodeCoverage YES -derivedDataPath build
      - name: Build UI Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild build-for-testing -project Sparkle.xcodeproj -scheme UITests -configuration Debug -derivedDataPath build
      - name: Run UI Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild test-without-building -project Sparkle.xcodeproj -scheme UITests -configuration Debug -derivedDataPath build

      - name: Analyze Sparkle
        if: ${{ matrix.run-analyzer && github.event_name == 'pull_request' }}
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
            xcodebuild analyze -project Sparkle.xcodeproj -quiet -scheme Sparkle -configuration Release -derivedDataPath analyze > analyze_output.txt
            
      - name: Find Analyzed Warnings
        if: ${{ success() && matrix.run-analyzer && github.event_name == 'pull_request' }}
        id: findwarnings
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
            if grep "warning:" analyze_output.txt | grep -q -v "dependency scan of"; then
                echo "analyzestatus=0" >> $GITHUB_OUTPUT
            else
                echo "analyzestatus=1" >> $GITHUB_OUTPUT
            fi
        
      - name: Extract Analyzed Warnings
        if: ${{ success() && matrix.run-analyzer && github.event_name == 'pull_request' && steps.findwarnings.outputs.analyzestatus == '0' }}
        id: warnings
        run: |
            {
                echo 'content<<EOF'
                cat analyze_output.txt
                echo 'EOF'
            } >> $GITHUB_OUTPUT
      
      - name: Post Analyzed Warnings
        if: ${{ success() && matrix.run-analyzer && github.event_name == 'pull_request' && steps.findwarnings.outputs.analyzestatus == '0' }}
        uses: mshick/add-pr-comment@v2
        with:
            allow-repeats: false
            message: "``` ${{ steps.warnings.outputs.content }} ```"
        
      - name: Build Release Distribution
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild build -project Sparkle.xcodeproj -scheme Distribution -configuration Release -derivedDataPath build
      - name: Archive Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build/Logs
      - name: Upload Distribution
        if: ${{ success() && matrix.upload-dist }}
        uses: actions/upload-artifact@v4
        with:
          name: Sparkle-distribution-${{ matrix.xcode }}.tar.xz
          path: build/Build/Products/Release/sparkle_dist.tar.xz
